from .schemas import (
    # Laboratoires
    LaboratoireBase,
    LaboratoireCreate,
    LaboratoireUpdate,
    LaboratoireResponse,
    # Presentations
    PresentationBase,
    PresentationCreate,
    PresentationResponse,
    # Catalogue
    CatalogueProduitBase,
    CatalogueProduitCreate,
    CatalogueProduitUpdate,
    CatalogueProduitResponse,
    # Regles Remontee
    RegleRemonteeCreate,
    RegleRemonteeResponse,
    # Ventes
    MesVentesResponse,
    # Import
    ImportResponse,
    ExtractionPDFRequest,
    ExtractionPDFResponse,
    LigneExtraite,
    # Scenarios
    ScenarioCreate,
    ScenarioResponse,
    ResultatSimulationResponse,
    TotauxSimulation,
    # Comparaison
    ComparaisonScenarios,
    ScenarioTotaux,
    # Parametres
    ParametreResponse,
    ParametreUpdate,
    # Matching (Legacy)
    MatchCandidat,
    MatchingResult,
    # Matching Intelligent
    MatchResultItem,
    VenteMatchingItem,
    ProcessSalesRequest,
    ProcessSalesResponse,
    LabMatchingSummary,
    AnalyzeMatchRequest,
    AnalyzeMatchResponse,
    ExtractedComponents,
    # Simulation avec Matching
    SimulationWithMatchingRequest,
    SimulationWithMatchingResponse,
    SimulationLineResult,
    # Coverage & Combo
    LabRecoveryInfo,
    BestComboResult,
    BestComboResponse,
    # Reports
    ReportRequest,
)

__all__ = [
    "LaboratoireBase",
    "LaboratoireCreate",
    "LaboratoireUpdate",
    "LaboratoireResponse",
    "PresentationBase",
    "PresentationCreate",
    "PresentationResponse",
    "CatalogueProduitBase",
    "CatalogueProduitCreate",
    "CatalogueProduitUpdate",
    "CatalogueProduitResponse",
    "RegleRemonteeCreate",
    "RegleRemonteeResponse",
    "MesVentesResponse",
    "ImportResponse",
    "ExtractionPDFRequest",
    "ExtractionPDFResponse",
    "LigneExtraite",
    "ScenarioCreate",
    "ScenarioResponse",
    "ResultatSimulationResponse",
    "TotauxSimulation",
    "ComparaisonScenarios",
    "ScenarioTotaux",
    "ParametreResponse",
    "ParametreUpdate",
    "MatchCandidat",
    "MatchingResult",
    "MatchResultItem",
    "VenteMatchingItem",
    "ProcessSalesRequest",
    "ProcessSalesResponse",
    "LabMatchingSummary",
    "AnalyzeMatchRequest",
    "AnalyzeMatchResponse",
    "ExtractedComponents",
    "SimulationWithMatchingRequest",
    "SimulationWithMatchingResponse",
    "SimulationLineResult",
    "LabRecoveryInfo",
    "BestComboResult",
    "BestComboResponse",
    "ReportRequest",
]
